mil2kil: main.o miles2kilFuncs.o
	g++ -g -Wall main.o miles2kilFuncs.o -o mil2kil

main.o: main.cpp miles2kilFuncs.hpp
	g++ -g -Wall -c main.cpp

miles2kilFuncs.o: miles2kilFuncs.cpp
	g++ -g -Wall -c miles2kilFuncs.cpp